site_name: ISDN 2602 Teaching Team User Manual
theme:
    name: material
    features:
        - content.code.copy
markdown_extensions:
    - pymdownx.pathconverter:
          base_path: "/TeachingTeamUserManual"
          relative_path: ""
          absolute: true
          tags: "a script link object embed"
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
